import { Avatar } from "@chakra-ui/avatar";
import { Tooltip } from "@chakra-ui/tooltip";
import ScrollableFeed from "react-scrollable-feed";
import {
  isLastMessage,
  isSameSender,
  isSameSenderMargin,
  isSameUser,
} from "../config/ChatLogics";
import { ChatState } from "../Context/ChatProvider";

const ScrollableChat = ({ messages }) => {
  const { user } = ChatState();
  console.log(messages, "mess");
  return (
    <>
      {/* {messages &&
        messages.map((m, i) => (
          <>
            <span
              style={{
                backgroundColor: `${
                  m.sender._id === user._id ? "#BEE3F8" : "#B9F5D0"
                }`,
                marginLeft: isSameSenderMargin(messages, m, i, user._id),
                marginTop: isSameUser(messages, m, i, user._id) ? 3 : 10,
                borderRadius: "20px",
                padding: "5px 15px",
                maxWidth: "75%",
              }}
            >
              {m.content}
            </span>
          </>
          
        ))} */}
      <span>abc1</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abc</span>
      <span>abcL</span>
    </>
  );
};

export default ScrollableChat;
